[[redirects]]
  from = "/alumniweekend/2020/events"
  to = "https://calendar.ucsc.edu/alumni_weekend"
  status = 301

[[redirects]]
  from = "/alumniweekend/2020/"
  to = "/"
  status = 200

  [[redirects]]
    from = "/alumniweekend/"
    to = "/"
    status = 200
